In [112]:
import pandas as pd
import numpy as np

In [180]:
df = pd.read_csv('choCuong.csv')
dfnp = df.to_numpy()

In [181]:
matrix = []
row = [dfnp[0]]
rdx, idx = 0, 1
while idx < len(dfnp):
    if row[rdx][7] == dfnp[idx][7]:
        row.append(dfnp[idx])
        rdx += 1  
    else:
        matrix.append(row)
        row = [dfnp[idx]]
        rdx = 0
    idx += 1
    if idx == len(dfnp) - 1:
        matrix.append(row)  
for idx in range(len(matrix)):
    matrix[idx] = [matrix[idx]]

In [182]:
def get_min_nmatrix(rnmatrix):
    list_nmatrix = [min(x, key=lambda df: df[1]) for x in rnmatrix]
    resmin = list_nmatrix[0]
    for kdx in range(1,len(list_nmatrix)):
        if resmin[7] > list_nmatrix[kdx][7]:
            resmin = list_nmatrix[kdx]
    return resmin

def get_max_nmatrix(rnmatrix):
    list_nmatrix = [max(x, key=lambda df: df[3]) for x in rnmatrix]
    resmax = list_nmatrix[0]
    for kdx in range(1,len(list_nmatrix)):
        if resmax[7] < list_nmatrix[kdx][7]:
            resmax = list_nmatrix[kdx]
    return resmax

In [183]:
status = False
while not status:
    nmatrix = [matrix[0]]
    idnmatrix = 0
    status = True
    for idx in range(1,len(matrix)):
        rmin = get_min_nmatrix(nmatrix[idnmatrix])
        rnmax = get_max_nmatrix(matrix[idx])

        delta_r_rn = rmin[1] - rnmax[3]

        if delta_r_rn > 10:
            nmatrix.append(matrix[idx])
            idnmatrix = idnmatrix + 1
        else:
            nmatrix[len(nmatrix)-1].append(matrix[idx][0])  
            idnmatrix = len(nmatrix) - 1
            status = False
    matrix = nmatrix

In [186]:
nmatrix[1]

[[array([131.99606323242188, 539.55517578125, 205.35971069335935,
         644.4609375, 0.9057504534721376, 0, 'Lon Lager', 3], dtype=object),
  array([195.8841094970703, 427.7530212402344, 267.38726806640625,
         650.8338623046875, 0.910524845123291, 7, 'Chai Chill', 3],
        dtype=object),
  array([257.7524108886719, 450.2332153320313, 315.2636413574219,
         647.6859741210938, 0.9050107598304749, 11, 'Chai Xa xi', 3],
        dtype=object),
  array([313.6437072753906, 437.48236083984375, 371.4527282714844,
         650.6991577148438, 0.9301877021789552, 1, 'Chai Export', 3],
        dtype=object),
  array([369.7073669433594, 435.638916015625, 429.7226257324219,
         654.1845703125, 0.9289765357971193, 1, 'Chai Export', 3],
        dtype=object),
  array([431.6911315917969, 435.4360961914063, 492.8844909667969,
         654.3075561523438, 0.9423456788063048, 2, 'Chai Larger', 3],
        dtype=object),
  array([492.6997680664063, 455.4903564453125, 545.4440307617188,


In [178]:
import copy 
final_matrix = []

nnmatrix = copy.deepcopy(nmatrix)
for idx in range(len(nnmatrix)):
    submatrix = [[x[5] for x in nmatrix[idx][0]]]
    lnmatrix0 = len(nnmatrix[idx][0])
    for jdx in range(1,len(nnmatrix[idx])):
        none_list = [None]*lnmatrix0
        for kdx in range(len(nnmatrix[idx][jdx])):
            center =  (nnmatrix[idx][jdx][kdx][0] + nnmatrix[idx][jdx][kdx][2])/2
            r0dx = 0
            while r0dx < lnmatrix0: 
                if center > nnmatrix[idx][0][r0dx][0] and center < nnmatrix[idx][0][r0dx][2]:
                    none_list[r0dx] = nnmatrix[idx][jdx][kdx][5]
                    break
                r0dx = r0dx + 1
        submatrix.append(none_list)
    final_matrix.append(submatrix)
        

In [179]:
for idx in range(len(final_matrix)-1, -1, -1):
    print(f'Rack {len(final_matrix)- idx}')
    for jdx in range(len(final_matrix[idx])-1, -1, -1):
        print(final_matrix[idx][jdx])

Rack 1
[0, 5, None, None, None, None, 9, None]
[0, 5, 8, 8, 3, 3, 9, 4]
Rack 2
[0, None, None, None, None, None, None, None, None, None]
[0, 7, 11, 1, 1, 2, 11, 2, 7, 7]
Rack 3
[6, 12, 12, 10, 10, 4, 4]
